name: Build and Deploy LiveKit Connector

on:
  push:
    branches:
      - main
      - develop
    # Only deploy when a tag is pushed that matches the pattern v*
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test
  
  build:
    name: Build Docker image
    needs: test
    runs-on: ubuntu-latest
    # Only run this job if the tests passed and we're on main or a tag was pushed
    if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: spatialchat/source-livekit
          # Use the tag if it exists, otherwise use the branch name
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      
      - name: Build Docker image (without push)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    name: Deploy to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    # Only run this job if the build succeeded and we're pushing a tag
    if: success() && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: spatialchat/source-livekit
          # Use the tag if it exists, otherwise use the branch name
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            # Also tag as 'latest' when it's a release
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Update deployment status
        run: |
          echo "Deployed LiveKit connector to Docker Hub with tags: ${{ steps.meta.outputs.tags }}"
